name: Bibliothèque CI/CD - Dépendances

on:
  workflow_call:

jobs:
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    env:
      TRIVY_VERSION: 0.69.1
      REGISTRY: ghcr.io
      CI: true
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Set owner to lowercase
        run: |
          echo "IMAGE_PREFIX=ghcr.io/$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Display Trivy version
        run: |
          echo "Le scan sera fait avec $(docker run --rm aquasec/trivy:${TRIVY_VERSION} version)"

      - name: Run Trivy scan on backend
        run: |
          BACKEND_IMAGE="${IMAGE_PREFIX}/backend:latest"

          echo "Scanning ${BACKEND_IMAGE}..."
          docker pull "${BACKEND_IMAGE}"

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:${TRIVY_VERSION} \
            image \
            --severity HIGH,CRITICAL \
            "${BACKEND_IMAGE}"

      - name: Run Trivy scan on frontend
        run: |
          FRONTEND_IMAGE="${IMAGE_PREFIX}/frontend:latest"

          echo "Scanning ${FRONTEND_IMAGE}..."
          docker pull "${FRONTEND_IMAGE}"

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:${TRIVY_VERSION} \
            image \
            --severity HIGH,CRITICAL \
            "${FRONTEND_IMAGE}"
