name: Bibliothèque Spring Angular - Lint
on:
  workflow_call:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Lint Backend with Checkstyle
        run: |
          cd Bibliotheque-Back/Bibliotheque
          chmod +x mvnw
          ./mvnw checkstyle:check -Dcheckstyle.config.location=checkstyle.xml

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Lint Frontend with ESLint
        run: |
          cd Bibliotheque-Front
          npm ci
          npm i eslint @eslint/js typescript-eslint
          npx eslint "src/**/*.{ts,tsx}"
