name: Bibliothèque CI/CD

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

jobs:
  publish-image:
    uses: ./.github/workflows/publish-image.yml
  tests:
    uses: ./.github/workflows/test.yml
    needs: [publish-image]
  dependances:
    uses: ./.github/workflows/dependance.yml
    needs: [tests]
  documentation:
    uses: ./.github/workflows/doc.yml
    needs: [tests]
