name: Bibliothèque CI/CD

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  dependances:
    uses: ./.github/workflows/dependance.yml
    needs: [tests]
  documentation:
    uses: ./.github/workflows/doc.yml
    needs: [tests]
