name: Bibliothèque CI/CD - Publish Image

on:
  workflow_call:

jobs:
  publish-image:
    name: Publish Docker Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io

    steps:
      - uses: actions/checkout@v5

      - name: Set owner to lowercase
        id: owner
        run: |
          echo "value=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build and push backend image
        run: |
          BACKEND_IMAGE="ghcr.io/${{ steps.owner.outputs.value }}/backend:latest"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "${BACKEND_IMAGE}" \
            --push \
            Bibliotheque-Back/Bibliotheque

      - name: Build and push frontend image
        run: |
          FRONTEND_IMAGE="ghcr.io/${{ steps.owner.outputs.value }}/frontend:latest"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "${FRONTEND_IMAGE}" \
            --push \
            Bibliotheque-Front
